#ifndef BUBBA_3D_CONSTANTS_H
#define BUBBA_3D_CONSTANTS_H

#define UNIFORM_BUFFER_OBJECT_MATRICES_NAME "Matrices"
#define UNIFORM_BUFFER_OBJECT_MATRICES_INDEX 0


#define SIMPLE_SHADER_NAME "simple_shader"

#define POST_FX_SHADER_NAME  "POST_FX_SHADER"
#define VERTICAL_BLUR_SHADER_NAME  "VERTICAL_BLUR_SHADER"
#define HORIZONTAL_BLUR_SHADER_NAME  "HORIZONTAL_BLUR_SHADER"
#define CUTOFF_SHADER_NAME  "CUTOFF_SHADER"
#define FRAME_BUFFER_CHANGE_SHADER_NAME  "FRAME_BUFFER_SHADER"

#define DEFAULT_FRAMEBUFFER_ID 0



#endif //BUBBA_3D_CONSTANTS_H
